# -*- coding: utf-8 -*-
"""Nicholas Stamatakis CSE 101 Lab Exercises Set #3: if-statements

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ggvgb1GjHoeX2G11fTKzP5WCI6H2M6h5

#CSE 101: Computer Science Principles

####Stony Brook University, Summer 2021, Session I Extended

### Lab Exercises Set #3

#### Due: Sunday, June 6, 2021 at 11:59 pm EDT

### Learning Outcomes
By the end of these exercises you should be able to:
* Write short code fragments that use if-statements:
    * with only an if-clause
    * with an if-clause and an else-clause
    * with an if-clause and one or more elif-clauses

### if-statements

E1. Create a variable `total` and store a positive integer in it. Write a Boolean expression that evaluates to `True` only when `total` is divisible by 4. You do not need to write an if-statement.
"""

total=5
total % 4 == 0

"""E2. Create a variable `length` and store a positive integer in it. Write an if-statement that displays the string `'long'` if `length` is greater than 100 and `'short'`, otherwise."""

length=101
if length > 100:
    print('long')
else:
    print('short')

"""E3. Create a variable `age` and store a positive integer in it. Write an if-statement that displays the string `'adult'` if `age` is in the range 18-64 (inclusive), and `'other`', otherwise. (Hint: use the `a <= x <= b` notation.)"""

age=65
if 18 <= age <= 64:
    print('adult')
else:
    print('other')

"""E4. The marginal state income tax rates in [Kansas](https://www.incometaxpro.net/tax-rates/kansas.htm) for single people are:

| | Range| |Tax Rate|
|---------|-----|---------|-------|
| \$0      | to  | \$15,000 | 3.1%  |
| \$15,001 | to  | $30,000 | 5.25% |
| \$30,001 | and | up      | 5.7%  |

For example, someone who earns \$35,000 will pay 3.1% tax on the first $15,000 of her salary, 5.25% on the next \$15,000, and 5.7% on the remaining income. Complete the function `compute_tax` that uses a multiway if-statement to compute and return the total tax due for the salary stored in the argument named `salary`. Test your code for each of the following salaries:
* \$35,000 (tax due should be \$1,537.50)
* \$25,000 (tax due should be \$990.00)
* \$5,000 (tax due should be \$155.00)

"""

def compute_tax(salary):
    if salary >= 30001:
        tax=15000 * 0.031 + 15000 * 0.0525 + (salary-30000) * 0.057
        return tax
    elif salary >=15001:
        tax=15000 * 0.031 + (salary-15000) * 0.0525
        return tax
    else:
        tax=salary*0.031
        return tax

compute_tax(35000)

compute_tax(25000)

compute_tax(5000)

"""E5. What happens if you provide a negative value for `salary`? Make a copy of your `compute_tax` function below and modify it so that the function to return `-1.0` if `salary` is negative."""

def compute_tax(salary):
    if salary >= 30001:
        tax=15000 * 0.031 + 15000 * 0.0525 + (salary-30000) * 0.057
        return tax
    elif salary >= 15001:
        tax=15000 * 0.031 + (salary-15000) * 0.0525
        return tax
    elif salary >= 0:
        tax=salary*0.031
        return tax
    else:
        return -1.0

"""E6. Now call your revised function with the same test cases as before (`35000`, `25000`, `5000`), as well as a negative number for `salary`."""

compute_tax(35000)

compute_tax(25000)

compute_tax(5000)

compute_tax(-2000)

"""E7. Using nested if-statements, write a function that returns the move ticket price for a customer. The pricing guide is as follows, with variables storing the values of interest highlighted in the rules:
* if `today` is Monday and the customer's `age` is more than 64, the price is \$10
* if `today` is Monday and the customer's `age` is not more than 64, the price is \$15
* if `today` is not Monday and the customer's `age` is more than 64, the price is \$12
* if `today` is not Monday and the customer's `age` is not more than 64, the price is \$17

You may not use the `and` operator for this exercise; you must use if-statements.
"""

def movie_ticket(today,age):
    if today == "Monday":
        if age > 64:
            ticket_price=10
            return ticket_price
        else:
            ticket_price=15
            return ticket_price
    else:
        if age > 64:
            ticket_price=12
            return ticket_price
        else:
            ticket_price=17
            return ticket_price

print(movie_ticket("Monday", 65))
print(movie_ticket("Monday", 63))
print(movie_ticket("Tuesday", 65))
print(movie_ticket("Tuesday", 63))

"""E8. Test your code by calling `movie_ticket` four times with arguments so that each return value is different. Display the return value in each case."""

price = movie_ticket('Wednesday', 15)  # example #1
price

price = movie_ticket('Wednesday', 65)  # example #2
price

price = movie_ticket('Monday', 15)  # example #3
price

price = movie_ticket('Monday', 65)  # example #4
price

"""### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse101sum/schedule-session-i).

1. Click the **Submit** link for this assignment.

1. Type your Net ID (Blackboard login) on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.
"""