# -*- coding: utf-8 -*-
"""Nicholas Stamatakis CSE 101 Lab Exercises Set #7: Lists and Iteration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezTzAO57i7UH1bfMEqIq5KBVomc1Mgzf

#CSE 101: Computer Science Principles

####Stony Brook University, Summer 2021, Session I Extended

### Lab Exercises Set #7

#### Due: Sunday, June 20, 2021 at 11:59 pm EDT

### Learning Outcomes
By the end of these exercises you should be able to:
* Write short code segments that iterate over lists of values.

### Iterating Over Lists

E1. Define a variable called `scores` and store inside it 7 or 8 integers in the range 1 through 100 (inclusive). Include some values near 0 and some values near 100.
"""

scores=[2, 5, 7, 13, 25, 89, 95, 99]

"""E2. Use a for-loop to compute the total of those values greater than 50. Display the sum. """

sum=0
for i in scores:
    if i > 50:
        sum += i
print(sum)

"""E3. Use a for-loop and the `enumerate` function to print the indices of those scores greater than 50. """

scores=[2, 5, 7, 13, 25, 89, 95, 99]
for i, scores in enumerate(scores):
    if scores > 50:
        print(i)

"""E4. Use a for-loop to replace all values greater than 50 with `0`. Then display the updated contents of `scores`."""

scores=[2, 5, 7, 13, 25, 89, 95, 99]
for i in range(len(scores)):
    if scores[i] > 50:
        scores[i]=0
print(scores)

"""E5. Create a list called `titles` and store in it a list of 5 book titles."""

titles = ['Harry Potter', 'Percy Jackson', 'Hunger Games', 'Loserthink', 'Zero to One']

"""E6. Use a for-loop to print the last character of each string in `titles`."""

for i in range(len(titles)):
    print(titles[i][-1])

"""E7. Create two lists: a list of 5 first names and a list of 5 last names. Using a for-loop and `zip`, print 5 full names produced by concatenating a first name and last name from each list. Pull each name (one first name, one last name) from the same position (index) from each list."""

first_names=['Nick', 'Rick', 'John', 'Bob', 'Mike']
last_names=['Stamatakis', 'Smith', 'Antetokoumpo', 'Harden', 'Irving']
full_names=[]
for f,l in zip(first_names, last_names):
    full_names.append(f + ' ' + l)
print(full_names)

"""### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse101sum/schedule-session-i).

1. Click the **Submit** link for this assignment.

1. Type your Net ID (Blackboard login) on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.
"""