# -*- coding: utf-8 -*-
"""Nicholas Stamatakis CSE 101 Lab Exercises Set #10: Dictionaries and Files

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpneQK1AWJ3RZUhKung8sXnogkOC9I9q

#CSE 101: Computer Science Principles

####Stony Brook University, Summer 2021, Session I Extended

### Lab Exercises Set #10

#### Due: Sunday, July 4, 2021 at 11:59 pm EDT

### Learning Outcomes
By the end of these exercises you should be able to:
* Write short code segments to create, access and update dictionaries.
* Write short code segments to read and write CSV files.

### Dictionaries

E1. Create a dictionary `inventory` that maps a type of fruit to a count of how many are available at a fruit stand:

* 23 apples (use `'apples'` as the key)
* 14 pears
* 8 bananas
* 20 oranges
"""

inventory={
    'apples': 23,
    'pears': 14,
    'bananas': 8,
    'oranges': 20,
}

"""E2. Display the entire contents of the dictionary."""

print(inventory)

"""E3. Display the current number of apples on-hand at the fruit stand."""

print(inventory['apples'])

"""E4. The fruit stand owner just got a shipment of 10 more apples. In one line of code, use the `[]` operator look up the current number of apples on-hand, add 10 to that number using `+=`, and update the number of apples stored in the dictionary."""

inventory['apples'] += 10
print(inventory['apples'])

"""E5. Display the entire contents of the updated dictionary."""

print(inventory)

"""E6. Delete the key/value pair associated with oranges in the dictionary."""

del inventory['oranges']
print(inventory)

"""E7. The fruit stand owner just got a shipment of 15 lemons. Update the `inventory` dictionary accordingly."""

inventory['lemons'] = 15

"""E8. Display the entire contents of the updated dictionary."""

print(inventory)

"""E9. Write a for-loop that increases the number of every fruit on-hand by 5."""

for fruit in inventory:
    inventory[fruit] += 5

"""E10. Display the entire contents of the updated dictionary.


"""

print(inventory)

"""E11. Write an if-else statement that prints `Yes` if `'grapes'` is in the dictionary, and `No`, otherwise."""

if 'grapes' in inventory:
    print('Yes')
else:
    print('No')

"""E12. Use one of the techniques from the lecture notes for writing a dictionary to disk to save the contents of the `inventory` dictionary in a file named `inventory.csv`."""

import csv

fieldnames=['apples', 'pears', 'bananas', 'lemons']
fruits={'apples': 38, 'pears':19, 'bananas':13, 'lemons':20}

with open('inventory.csv', 'w') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames)
    writer.writeheader()
    writer.writerow(fruits)

"""E13. Use one of the techniques from the lecture notes for reading a CSV from disk and use it to convert the contents of `inventory.csv` into a dictionary named `inventory_saved`."""

import csv
import itertools

inventory_saved=[]

with open('inventory.csv', encoding='utf-8-sig') as csvfile:
    reader = csv.reader(csvfile)
    inventory_saved=[]
    for row in reader:
        inventory_saved.append(row)
    inventory_saved=list(itertools.chain(*inventory_saved))
    fruits = inventory_saved[0:4]
    amounts = inventory_saved[4:]
    inventory_saved = {fruits[i]: amounts[i] for i in range(len(fruits))}

"""E14. Display the contents of the `inventory_saved` dictionary to check that the original dictionary was correctly saved to disk and also then loaded from disk into a new dictionary."""

print(inventory_saved)
#Yes, it contains the sames key-value pairs as the original dictionary

"""### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse101sum/schedule-session-i).

1. Click the **Submit** link for this assignment.

1. Type your Net ID (Blackboard login) on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.
"""