# -*- coding: utf-8 -*-
"""Nicholas Stamatakis CSE 101 Lab Exercises Set #8: Logical Operators and While-loops

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFDlJM9dNqoyGgxHG78WDUsHDWS-GFhv

#CSE 101: Computer Science Principles

####Stony Brook University, Summer 2021, Session I Extended

### Lab Exercises Set #8

#### Due: Sunday, June 27, 2021 at 11:59 pm EDT

### Learning Outcomes
By the end of these exercises you should be able to:
* Write short code segments that use logical operators.
* Write short code segments containing a while-loop.

### Logical Operators

E1. Write a code fragment that checks if the integer stored in a variable `x` is divisible by 2 and, if so, print "Even"; otherwise, print "Odd". Write your own test cases to check the correctness of your code: one for an even value for `x`, and one for an odd value of `x`.
"""

x = 5  # replace this with different values for x to check your work
if x % 2 == 0:
    print('Even')
else:
    print('Odd')

x = 3 
if x % 2 ==0:
    print('Even')
else:
    print('Odd')

x = 4 
if x % 2 == 0:
    print('Even')
else:
    print('Odd')

"""E2. Write a code fragment that checks if the value stored in a variable `x` is divisible by 2 or 7, and, if so, print "Divisible"; otherwise, print "Not divisible". Try the four test cases below to check the correctness of your code."""

x = 5
if x % 2 == 0 or x % 7 == 0:
    print('Divisible')
else:
    print('Not divisible')

x = 4
if x % 2 == 0 or x % 7 == 0:
    print('Divisible')
else:
    print('Not divisible')

x = 21
if x % 2 == 0 or x % 7 == 0:
    print('Divisible')
else:
    print('Not divisible')

x = 28
if x % 2 == 0 or x % 7 == 0:
    print('Divisible')
else:
    print('Not divisible')

"""E3. Write a code that checks if the string stored in a variable `x` is at least 10 characters long and starts with the letter Q. If so, print "Pass"; otherwise, print "Fail". Write your own test cases to check the correctness of your code."""

x = 'SBU'
if len(x) >= 10 and x[0] == 'Q':
    print('Pass')
else:
    print('Fail')

x = 'QBU'
if len(x) >= 10 and x[0] == 'Q':
    print('Pass')
else:
    print('Fail')

x = 'QBUQBUQBUU'
if len(x) >= 10 and x[0] == 'Q':
    print('Pass')
else:
    print('Fail')

x = 'ABCDQBUQBUQBUU'
if len(x) >= 10 and x[0] == 'Q':
    print('Pass')
else:
    print('Fail')

"""E4. Write a code fragment that tests if the string stored in a variable `x` starts with the letters X, Y or Z. If so, print "Pass"; otherwise, print "Fail"."""

x = 'SBU'
if x[0] == 'X' or x[0] == 'Y' or x[0] == 'Z':
    print('Pass')
else:
    print('Fail')

x = 'ZBU'
if x[0] == 'X' or x[0] == 'Y' or x[0] == 'Z':
    print('Pass')
else:
    print('Fail')

x = 'ZBU'
if x.startswith('X') or x.startswith('Y') or x.startswith('Z'):
    print('Pass')
else:
    print('Fail')

#I wrote this to show another way to accomplish the same purpose.

"""E5. Write a code fragment that checks if the string stored in a variable `x` starts with the letters X, Y or Z and ends with the letter A. If so, print "Pass"; otherwise, print "Fail". Write your own test cases to check the correctness of your code."""

x = 'ZBU'
if (x[0] == 'X' or x[0] == 'Y' or x[0] == 'Z') and (x[-1] == 'A'):
    print('Pass')
else:
    print('Fail')

x = 'YBUA'
if (x[0] == 'X' or x[0] == 'Y' or x[0] == 'Z') and (x[-1] == 'A'):
    print('Pass')
else:
    print('Fail')

x = 'ZBUA'
if (x.startswith('X') or x.startswith('Y') or x.startswith('Z')) and (x.endswith('A')):
    print('Pass')
else:
    print('Fail')

#I wrote this to show another way to accomplish the same purpose.

"""### While-loops

E6. Write code containing a while-loop that prints the first 5 multiples of 4, starting with 4 itself.
"""

x = 4
n=1
while n <= 5:
    y= x * n
    n += 1
    print(y)

"""E7. Write code containing a while-loop that prints all values in the list `nums` that are less than or equal to 10 **and** divisible by 3. Write your own test cases (i.e., different `nums` lists) to check the correctness of your code.


"""

nums = [1, 3, 45, 5, 9, 50, 60, 6, 30]
i=0
while i < len(nums):
    if (nums[i] <= 10) and (nums[i] % 3 == 0):
        print(nums[i])
    i += 1

nums = [0, 6, 9, 12, 66, 72, 99, -3, -9, -77]
i=0
while i < len(nums):
    if (nums[i] <= 10) and (nums[i] % 3 == 0):
        print(nums[i])
    i += 1

"""E8. Use a while-loop to re-write the following code so that your code generates the same result."""

for i in range (-5, 3):
    print(i)

n=-5
while n >= -5 and n <= 2:
    print(n)
    n+=1

"""E9. Use a for-loop to re-write the following code so that your code generates the same result."""

name = 'Wolfie the Seawolf'
i = 0
while i < len(name):
    if name[i] in 'aeiou':
        print(name[i])
    i += 1

name = 'Wolfie the Seawolf'
for i in range(len(name)):
    if name[i] in 'aeiou':
        print(name[i])
    i += 1

"""### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse101sum/schedule-session-i).

1. Click the **Submit** link for this assignment.

1. Type your Net ID (Blackboard login) on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.
"""