# -*- coding: utf-8 -*-
"""Nicholas StamatakisCSE 101 Lab Exercises Set #4: String Basics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZqFgMb93T2TgCwyDBm003Qcr8q1nE8x

#CSE 101: Computer Science Principles

####Stony Brook University, Summer 2021, Session I Extended

### Lab Exercises Set #4

#### Due: Sunday, June 13, 2021 at 11:59 pm EDT

### Learning Outcomes
By the end of these exercises you should be able to:
* Use string operators and methods to perform basic operations with strings.

### String Concatenation and Repetition

E1. Define two strings, one that stores your first name, and another to store your last name.
"""

first_name = "Nicholas"
last_name = "Stamatakis"

"""E2. Write code that will concatenate your names with a space in between and then display the result."""

Full_name=first_name + " " +last_name
print(Full_name)

"""E3. Use the `*` operator to concatenate 10 copies of your first name together and display the result."""

print(first_name*10)

"""E4. Execute the following code:"""

dept = 'CSE'
code = 101
print(dept + code) # In this examle there will be a Type Error because you cannot concatenate a string with an integer.

"""Did Python do what you were expecting? Why did it do what it did?

E5. Execute the following code, which is similar to, but not the same as, the code above. 
"""

dept = 'CSE' #In the code above it ran exaclty as I had predicted, you cannot concatenate two different data types.
code = 101
print(dept + str(code))

"""Did Python do what you were expecting? Why did it do what it did?

### String Indexing

E6. Use the `len` function to compute and display the number of letters in your first name.
"""

num_letters=len(first_name)
print(num_letters)

"""E7. Use a non-negative index to extract and display the leftmost character of your first name."""

first_name[0]

"""E8. Use a positive index to extract and display the rightmost character of your first name."""

first_name[7]

"""E9. Use a negative index to extract and display the leftmost character of your first name."""

first_name[-8]

"""E10. Use a negative index to extract and display the rightmost character of your first name."""

first_name[-1]

"""E11. Use the `len` function to extract and display the rightmost character of your first name."""

first_name[len(first_name)-1]

"""E12. Write code that attempts to change the letter at index `1` of your first name to `Z`. Ask yourself: why doesn't this work?"""

first_name.replace(first_name[1], "Z") 
print(first_name) #It doesn't work because it doesn't change the value of the original variable.

"""E13. Define a new string that stores the words `Computer Science`."""

subject="Computer Science"

"""E14. Use slicing to extract and display the 3 leftmost characters of the string."""

subject[:3]

"""E15. Use slicing to extract and display the 5 rightmost characters of the string."""

subject[-5:]

"""E16. Use slicing to extract and display every 3rd character of the string, starting at index 2."""

subject[2::3]

"""E17. Use slicing display the string backwards."""

subject[::-1]

"""### String Methods

E18. Define a new string that stores the name `Donald Knuth`.
"""

name="Donald Knuth"

"""E19. Use `upper` to display the name in all uppercase."""

name.upper()

"""E20. Use `lower` to display the name in all lowercase."""

name.lower()

"""E21. Visit the official [documentation for Python string methods](https://docs.python.org/3/library/stdtypes.html#string-methods) and find a method that will capitalize every word in a string. (Hint: it's not `capitalize`!) Use it to display the string below in "title case". Do not simply modify the contents of the string below."""

country = 'united states of america'
print(country.upper())

"""E22. Write an expression to test whether the word `'the'` is present in the string named `country`."""

if 'the' in country:
    print('The word "the" is in the name of the country.')
else:
    print('The word "the" is not in the name of the country.')

"""E23. Use the `replace` method to replace all occurrences of the lowercase letter `e` in `country` with uppercase `E`, *but do not change the original string stored in* `country`. Instead, store the new string in a variable called `new_country`."""

new_country=country.replace("e", "E")
new_country

"""E24. Use the `count` method to count and display the number of lowercase letter `e` characters in `country`."""

print(country.count('e'))

"""E25. Using only the `strip` method and no slicing or other operators or methods, write code to remove the digit characters from the ends of the string below."""

message = '123454321YOU DID IT!678909876'
print(message.strip('1234567890'))

"""E26. Use the `find` method to determine and display the index of the leftmost occurrence of the substring `'abc'` in the string given below. (Hint: it should be `22`.)"""

letters = 'abdbdbababdbabbabdbacbabcdabadbaabcabdabcbdb'
print(letters.find('abc'))

"""E27. Use the `rfind` method to determine and display the index of the rightmost occurrence of the substring `'abc'` in the string given below. (Hint: it should be `38`.)"""

letters = 'abdbdbababdbabbabdbacbabcdabadbaabcabdabcbdb'
print(letters.rfind('abc'))

"""### Boolean Conditions Involving Strings

E28. Create a variable name `book` and store the string `'The Lord of the Rings'` in that variable.
"""

book="The Lord of the Rings"

"""E29. Write a single line of code that checks whether `book` begins with the string `'The'`."""

book.startswith('The')

"""E30. Write a single line of code that checks whether `book` ends with the string `'Onion Rings'`."""

book.endswith('Onion Rings')

"""### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse101sum/schedule-session-i).

1. Click the **Submit** link for this assignment.

1. Type your Net ID (Blackboard login) on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.
"""